### PR TITLE
Add Sanghavi2020 and SanghaviMurty2020

### PR DESCRIPTION
**Pull request by stothe2**

### CODE REVIEW

**Comment by mschrimpf** [comment]
result of https://github.com/brain-score/brainio_contrib/pull/27

**Comment by mschrimpf** [comment]
@franzigeiger and @jjpr-mit are fixing the jenkins unit test, let's wait to re-run and merge once successful.

**Comment by stothe2** [comment]
Adding SanghaviMurty2020 to this too (result of [brain-score/brainio_contrib#28](https://github.com/brain-score/brainio_contrib/pull/28))

**Comment by stothe2** [comment]
Closing this (carried over to [brain-score/braino_collection#37](https://github.com/brain-score/brainio_collection/pull/37)).

**Pull request closed without merging**
