### PR TITLE
ImageNet C overhaul

### PR DESCRIPTION
**Pull request by dapello**
Updated ImageNet C benchmark to only include 4 stimsets -- noise, blur, weather, and digital, instead of original 75 stimulus sets (gaussian_noise_1, gaussian_noise_2...)

### CODE REVIEW

**Comment by mschrimpf** [comment]
You can then delete the old lines from the `lookup.csv` I think.
Please also add the identifiers to unit tests, and ideally add a unit test to make sure everything looks okay -- see e.g. https://github.com/brain-score/brainio_collection/pull/45/files#diff-b9e46d9c3613f3b4f507f370cbf72ba443d33eb81a27d7f15fe81992f77ae370

**Comment by dapello** [comment]
added requested tests. My lookup.csv doesn't have the old lines -- not sure what's going on with that removal not being shown..?

**Comment by mschrimpf** [comment]
It might be because you haven't merged the most recent master, it's also complaining about conflicts. Maybe after merging, it will properly show

**Comment by mschrimpf** [comment]
Some of the unit tests are also failing:
`E   KeyError: 'label'` in e.g. `test_Dietterich_Hendrycks2019_noise` 

and an `AssertionError` in `test_list_stimulus_set` from a lack of commas here:
```
            'dietterich.Hendrycks2019.noise'
            'dietterich.Hendrycks2019.blur'
            'dietterich.Hendrycks2019.weather'
            'dietterich.Hendrycks2019.digital'
```
(see http://braintree.mit.edu:8080/job/unittest_brainio/207/console)

**Comment by dapello** [comment]
closed on account of github being weird. let's start from scratch.

**Pull request closed without merging**
